# Generated by Django 3.2.5 on 2022-09-09 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appoinments', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=255)),
                ('expiry_date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'SUPER_ADMIN'), ('ADMIN', 'ADMIN'), ('USER', 'USER'), ('DOCTOR', 'DOCTOR'), ('PATIENT', 'PATIENT')], default='USER', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date_and_time', models.DateTimeField()),
                ('prescription', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='+', serialize=False, to='appoinments.prescription')),
                ('appointment', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='appoinments.appointmentandavailability')),
                ('form_order', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='appoinments.createformorder')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='appoinments.pharmacy')),
            ],
        ),
        migrations.CreateModel(
            name='UserCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='users.countries')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'country')},
            },
        ),
        migrations.CreateModel(
            name='PharmacyVaccine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacy', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='appoinments.pharmacy')),
                ('vaccine', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='users.vaccine')),
            ],
            options={
                'unique_together': {('vaccine', 'pharmacy')},
            },
        ),
        migrations.CreateModel(
            name='PatientVaccine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_date', models.DateTimeField()),
                ('patient', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('pharmacy', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='appoinments.pharmacy')),
                ('vaccine', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='users.vaccine')),
            ],
            options={
                'unique_together': {('vaccine', 'pharmacy')},
            },
        ),
    ]
