# Generated by Django 3.2.5 on 2022-09-27 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220908_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useremailverification',
            name='code',
            field=models.PositiveIntegerField(),
        ),
    ]
