# Generated by Django 3.2.5 on 2022-09-27 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoinments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentandavailability',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
