# Generated by Django 3.2.5 on 2022-09-27 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoinments', '0002_appointmentandavailability_is_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentandavailability',
            name='can_access_SCR',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointmentandavailability',
            name='consult_copy_shared',
            field=models.BooleanField(default=False),
        ),
    ]
